import { EditContent, Footer, Header } from "@/components";
import Head from "next/head";

const EditList = () => {
	return (
		<>
			<Head>
				<title>Cart</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>

			<Header />
			<EditContent />
			<Footer />
		</>
	);
};

export default EditList;
