import { Footer, Header, MenuContent } from "@/components";
import Head from "next/head";

const Menu = () => {
	return (
		<>
			<Head>
				<title>Menu</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>

			<Header />
			<MenuContent />
			<Footer />
		</>
	);
};

export default Menu;
