import Head from "next/head";
import { Header } from "../components/";
import styled from "styled-components";

const MainContainer = styled.main`
	padding-top: 90px;
`;

export default function Home() {
	return (
		<>
			<Head>
				<title>Food delivery app</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<MainContainer>Home</MainContainer>
		</>
	);
}
