import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import toast, { Toaster } from "react-hot-toast";
import { Container, FormContainer } from "@/styles/pages/storesignup";

const StoreSignup = () => {
	const router = useRouter();
	const [data, setData] = useState({
		storeName: "",
		email: "",
		password: "",
		confirmPassword: "",
	});

	const handleOnChange = (e) => {
		const { name, value } = e.target;
		setData((preve) => {
			return { ...preve, [name]: value };
		});
	};

	const handleSubmit = async (e) => {
		e.preventDefault();
		const { storeName, email, password, confirmPassword } = data;
		if (storeName && email && password && confirmPassword) {
			if (password === confirmPassword) {
				const response = await fetch(`${process.env.NEXT_PUBLIC_SERVER_DOMAIN}/storesignup`, {
					method: "POST",
					headers: {
						"content-type": "application/json",
					},
					body: JSON.stringify(data),
				});

				const resData = await response.json();
				resData.message ? toast.success(resData.message) : toast.error(resData.error);

				if (resData.message) router.push("/login");
			} else {
				toast.error("Password and confirm password are not equal");
			}
		} else {
			toast.error("Please enter required fields");
		}
	};

	return (
		<>
			<Head>
				<title>Store sign up</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>

			<Container>
				<Toaster position="top-center" />
				<FormContainer>
					<h1>Store sign up</h1>
					<form onSubmit={handleSubmit}>
						<div>
							<label>Store name</label>
							<input type="text" id="storeName" name="storeName" value={data.storeName} onChange={handleOnChange} />
						</div>
						<div>
							<label>E-mail</label>
							<input type="email" id="email" name="email" value={data.email} onChange={handleOnChange} />
						</div>
						<div>
							<label>Create password</label>
							<input
								type="password"
								id="password"
								name="password"
								value={data.password}
								onChange={handleOnChange}
								minLength={6}
							/>
						</div>
						<div>
							<label>Confirm password</label>
							<input
								type="password"
								id="confirmPassword"
								name="confirmPassword"
								value={data.confirmPassword}
								onChange={handleOnChange}
								minLength={6}
							/>
						</div>
						<button type="submit">Sign up</button>
					</form>
					<p>
						Already have an account? <Link href="/login">Login page</Link>
					</p>
					<p>
						Would you like to be <Link href="/signup">user</Link>?
					</p>
					<p>
						Just visit to <Link href="/">Home page</Link>
					</p>
				</FormContainer>
			</Container>
		</>
	);
};

export default StoreSignup;
